"""extend_catalog_v160.py — v1.6.0 catalog expansion

Appends a much larger curated list of Bollywood, Hollywood and TV titles
to data/movies.json. Idempotent — skips IDs already present.

Goal: take the catalog from ~149 → 400+ entries so premium users get a
genuinely deep pool to scroll through. The vibe pipeline runs separately
afterwards to fill in vibe_endings for each new movie. Until that
finishes, premium feed hides any movie with zero vibe endings (handled
in backend/premium.go).
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "data" / "movies.json"


def H(id_, title, year, rating, genre, syn, end):
    return dict(id=id_, title=title, year=year, imdb_rating=rating,
                genre=genre, synopsis=syn, actual_ending=end,
                poster_url="", youtube_id="",
                region="hollywood", kind="movie")


def B(id_, title, year, rating, genre, syn, end):
    return dict(id=id_, title=title, year=year, imdb_rating=rating,
                genre=genre, synopsis=syn, actual_ending=end,
                poster_url="", youtube_id="",
                region="bollywood", kind="movie")


def TVI(id_, title, year, rating, genre, syn, end):
    return dict(id=id_, title=title, year=year, imdb_rating=rating,
                genre=genre, synopsis=syn, actual_ending=end,
                poster_url="", youtube_id="",
                region="bollywood", kind="tv")


def TVF(id_, title, year, rating, genre, syn, end, region="hollywood"):
    return dict(id=id_, title=title, year=year, imdb_rating=rating,
                genre=genre, synopsis=syn, actual_ending=end,
                poster_url="", youtube_id="",
                region=region, kind="tv")


NEW = []

# ---------------- Bollywood movies (deep cut, ~150 more) ----------------
NEW += [
    B("rang-de-basanti", "Rang De Basanti", 2006, 8.1, "Drama",
      "A British filmmaker travels to India to shoot a documentary on freedom fighters; the young cast is transformed by the parallels to their own corrupt times.",
      "After an honest pilot dies due to a defence scandal, the friends storm All India Radio, broadcast the truth and are gunned down."),
    B("dil-chahta-hai", "Dil Chahta Hai", 2001, 8.1, "Drama/Comedy",
      "Three best friends from Mumbai navigate love and growing apart in their twenties.",
      "Sid, Akash and Sameer reconcile at Tara's hospital bedside; Akash and Shalini reunite at last."),
    B("kabhi-khushi-kabhie-gham", "Kabhi Khushi Kabhie Gham", 2001, 5.5, "Family/Drama",
      "A wealthy patriarch disowns his adopted son for marrying outside their class; the family slowly drifts apart across continents.",
      "Rohan reunites the family in London after Yash sees them dance again."),
    B("kabhi-alvida-naa-kehna", "Kabhi Alvida Naa Kehna", 2006, 6.2, "Romance/Drama",
      "Two unhappily married New Yorkers begin an affair that fractures both households.",
      "Years later Dev and Maya meet again on the same train platform and finally start over together."),
    B("om-shanti-om", "Om Shanti Om", 2007, 6.7, "Drama/Romance",
      "A junior artist murdered in 1977 is reincarnated as a superstar bent on exposing his killer.",
      "Mukesh confesses on a haunted film set; chandelier falls on him just like Shanti's death."),
    B("don", "Don", 2006, 7.1, "Action/Thriller",
      "A police informant impersonates a slain crime lord to bust an international drug ring.",
      "Don himself was the real one all along — Roma realizes too late as he walks free with the encrypted disk."),
    B("don-2", "Don 2", 2011, 7.0, "Action/Thriller",
      "Don breaks out of a Malaysian prison and infiltrates Berlin's Euro printing plates heist.",
      "Don escapes Roma yet again, smirking at the camera with stolen plates."),
    B("agneepath-2012", "Agneepath", 2012, 7.2, "Action/Drama",
      "A man returns to Mandwa after fifteen years to take down the gangster who hanged his father.",
      "Vijay kills Kancha but is fatally stabbed; he dies in his mother's lap on the village beach."),
    B("dabangg", "Dabangg", 2010, 6.4, "Action/Comedy",
      "A swaggering, corrupt-but-good-hearted UP cop tangles with a politician on his home turf.",
      "Chulbul kills Chhedi Singh in a final showdown and reconciles with his estranged stepfather."),
    B("singham", "Singham", 2011, 7.1, "Action",
      "An honest Goa cop is transferred to a town ruled by a cruel MLA and decides to dismantle him.",
      "Singham forces Jaikant Shikre to publicly confess at gunpoint, then kills him on camera."),
    B("rowdy-rathore", "Rowdy Rathore", 2012, 5.8, "Action",
      "A petty thief discovers he's the lookalike of a slain encounter cop and takes up his mission.",
      "Vikram Rathore's lookalike kills the warlord and assumes his identity to raise the dead cop's daughter."),
    B("kahaani", "Kahaani", 2012, 8.1, "Thriller",
      "A pregnant woman lands in Kolkata searching for her missing husband during Durga Puja.",
      "Vidya is no widow — she's an avenger who poisons the Intelligence Bureau mole responsible for her real husband's death and vanishes."),
    B("queen", "Queen", 2014, 8.1, "Comedy/Drama",
      "A jilted Delhi bride goes on her honeymoon to Paris and Amsterdam alone and rediscovers herself.",
      "Rani returns the engagement ring to her ex-fiancé and walks out, free."),
    B("highway", "Highway", 2014, 7.7, "Drama",
      "A bride is kidnapped on her wedding eve; on the run she finds an unlikely solace with her captor.",
      "Mahabir is shot dead by police; Veera refuses to return to her old life and moves to the Himalayas."),
    B("haider", "Haider", 2014, 8.0, "Drama",
      "A young man returns to insurgency-torn Kashmir to find his missing father and uncovers his uncle's betrayal.",
      "Haider lets his uncle live to suffer, walking away from the cycle of revenge."),
    B("baahubali", "Baahubali: The Beginning", 2015, 8.0, "Action/Epic",
      "A young man raised by villagers learns he is the heir to a Mahishmati throne usurped by his cousin.",
      "Kattappa reveals he was forced to kill Amarendra Baahubali — Shiva swears revenge."),
    B("baahubali-2", "Baahubali 2: The Conclusion", 2017, 8.1, "Action/Epic",
      "Why Kattappa killed Baahubali — and how the heir reclaims his throne.",
      "Mahendra Baahubali kills Bhallaladeva and crowns himself; Devasena is freed after twenty-five years."),
    B("kgf-1", "K.G.F: Chapter 1", 2018, 7.9, "Action",
      "A poor Bombay slum boy promised his dying mother riches, grows into a feared assassin who infiltrates the Kolar Gold Fields.",
      "Rocky kills Andrews, takes over the goldfields and is crowned 'Rocky Bhai' by the slaves."),
    B("kgf-2", "K.G.F: Chapter 2", 2022, 8.2, "Action",
      "Rocky's grip on the goldfields tightens as the Indian government and rival Adheera plot his fall.",
      "Rocky sinks his ship full of gold rather than surrender; Inayat Khalil and Adheera are both dead."),
    B("rrr", "RRR", 2022, 7.8, "Action/Drama",
      "Two real-life Indian revolutionaries imagined as friends who later turn rivals under the British Raj.",
      "Bheem rescues the kidnapped girl; Ram is freed and they slaughter the British camp together."),
    B("pushpa", "Pushpa: The Rise", 2021, 7.6, "Action",
      "A coolie rises through Andhra's red-sandalwood smuggling syndicate by sheer cunning.",
      "Pushpa humiliates the corrupt SP by stripping in front of him, vowing this is only the beginning."),
    B("vikram", "Vikram", 2022, 8.4, "Action/Thriller",
      "A black-ops agent is reactivated to investigate a string of masked killings in Chennai.",
      "Vikram and his team eliminate the cartel; final scene reveals Rolex, hinting at a bigger universe."),
    B("master", "Master", 2021, 7.3, "Action",
      "An alcoholic college professor is transferred to a juvenile detention center ruled by a brutal don.",
      "JD beats Bhavani to death in a long-take fight and frees the boys from his grip."),
    B("super-deluxe", "Super Deluxe", 2019, 8.3, "Drama/Anthology",
      "Four interlinked Chennai stories about a transwoman parent, a porn-star wife, a porn boy and a god in the sky.",
      "All four threads converge: the wife buries the body, the trans parent is accepted, the boy reaches school, and the literal god watches benignly."),
    B("article-15", "Article 15", 2019, 8.1, "Crime/Drama",
      "An idealistic IPS officer is posted to a UP village after the rape and murder of two Dalit girls.",
      "Ayan finds the missing third girl alive in a sewer; he forces the upper-caste contractor to face the law."),
    B("andhadhun", "Andhadhun", 2018, 8.2, "Thriller",
      "A pretend-blind pianist becomes the only witness to a murder.",
      "Years later Akash, now actually-or-strategically blind, kicks a beer can in London — leaving the audience to guess if he killed Simi."),
    B("badhaai-ho", "Badhaai Ho", 2018, 7.7, "Comedy/Drama",
      "A middle-class Delhi family is mortified when the parents announce a surprise pregnancy.",
      "The whole family attends the baby's homecoming; Nakul and Renee finally bring their parents together."),
    B("stree", "Stree", 2018, 7.4, "Horror/Comedy",
      "In Chanderi, a witch abducts men who answer her call; only the sari-stitching tailor can stop her.",
      "Vicky learns Stree was a wronged courtesan; her shrine is built and the village finally respects her."),
    B("bhool-bhulaiyaa", "Bhool Bhulaiyaa", 2007, 7.4, "Horror/Comedy",
      "A New York psychiatrist visits his cousin's ancestral haveli to debunk a possession.",
      "Avni — not Radha — was the one truly possessed by Manjulika; Aditya exorcises her and the ghost is laid to rest."),
    B("masaan", "Masaan", 2015, 8.0, "Drama",
      "Two Banaras stories about caste, grief and shame eventually cross paths on the Sangam.",
      "Devi and Deepak meet on a boat at Allahabad — neither knowing the other, both finally able to breathe."),
    B("court", "Court", 2014, 7.8, "Drama",
      "A Mumbai folk singer is accused of inciting a sewage worker's suicide; the trial drags on absurdly.",
      "The judge dozes off on a beach holiday and slaps a child for waking him — the system endures, indifferent."),
    B("the-lunchbox", "The Lunchbox", 2013, 7.8, "Romance/Drama",
      "A Mumbai dabbawala mix-up sparks a letter exchange between a lonely housewife and a widowed accountant.",
      "Saajan and Ila never meet on screen; he leaves Mumbai for Bhutan, but her last note suggests she's coming after him."),
    B("english-vinglish", "English Vinglish", 2012, 7.7, "Drama",
      "A homemaker secretly enrolls in a New York English class to win her family's respect.",
      "Shashi gives her niece's wedding speech in English, reclaims her dignity and chooses her husband again on her own terms."),
    B("paa", "Paa", 2009, 7.0, "Drama",
      "A 12-year-old boy with a rare ageing disorder fights for his estranged parents to reunite.",
      "Auro dies after his parents' wedding; Vidya gives birth to a healthy girl named after him."),
    B("black", "Black", 2005, 8.1, "Drama",
      "A blind, deaf and mute girl's life is rewritten by her stubborn alcoholic teacher.",
      "Years later Michelle helps her now-amnesiac teacher remember the word 'water', repaying his gift."),
    B("guzaarish", "Guzaarish", 2010, 7.4, "Drama",
      "A quadriplegic magician fights in court for the right to die.",
      "Ethan gets euthanasia approved by his loved ones at a private dinner instead of the court — his way."),
    B("rockstar", "Rockstar", 2011, 7.7, "Musical/Drama",
      "A naive Delhi college boy becomes a global rock icon while haunted by an unattainable love.",
      "Heer dies in Janardhan's arms; he plays one last anthem to a stadium that knows nothing of her."),
    B("tamasha", "Tamasha", 2015, 7.3, "Romance/Drama",
      "A man performing 'normal' for the world breaks down and tries to find the storyteller he was as a boy.",
      "Ved auditions his old self in front of a corporate jury — Tara watches, smiling at the man she always saw."),
    B("ye-jawaani-hai-deewani", "Yeh Jaawani Hai Deewani", 2013, 7.2, "Romance",
      "A workaholic boy and a free-spirited girl reunite years after a Manali trek for a wedding.",
      "Bunny chooses Naina at the wedding sangeet, finally trading his career compulsion for real life."),
    B("aashiqui-2", "Aashiqui 2", 2013, 6.9, "Musical/Romance",
      "A drunk has-been singer mentors a young girl into a star while spiraling himself.",
      "RJ kills himself to free Arohi from his shadow; she finishes their concert duet alone."),
    B("ek-villain", "Ek Villain", 2014, 7.0, "Thriller/Romance",
      "A reformed assassin hunts the serial killer who murdered his terminally-ill wife.",
      "Guru beats Rakesh to death after the latter's confession; Aisha's last wish list is fulfilled."),
    B("kabir-singh", "Kabir Singh", 2019, 7.0, "Romance/Drama",
      "A brilliant but volatile surgeon spirals into addiction after losing the love of his life.",
      "Preeti returns to Kabir, pregnant; they reunite at her grandfather's deathbed."),
    B("shershaah", "Shershaah", 2021, 8.4, "War/Biopic",
      "The life and Kargil heroism of Captain Vikram Batra.",
      "Vikram is killed at Point 4875 saving an injured comrade; the post is captured and named after him."),
    B("uri", "Uri: The Surgical Strike", 2019, 8.2, "War",
      "Indian para SF avenges the Uri attack via a surgical strike across the LoC.",
      "Major Vihaan and team destroy seven launchpads and return without a single casualty — 'How's the josh?'"),
    B("sardar-udham", "Sardar Udham", 2021, 8.4, "Biopic/Drama",
      "Sardar Udham Singh's twenty-year mission to assassinate Michael O'Dwyer for Jallianwala Bagh.",
      "Udham shoots O'Dwyer in Caxton Hall; he is hanged and his ashes are returned to India in 1974."),
    B("piku", "Piku", 2015, 7.6, "Comedy/Drama",
      "An architect daughter, her hypochondriac father and a cab company owner road-trip Delhi to Kolkata.",
      "Bhashkor dies peacefully after a bike ride in his ancestral home; Piku and Rana keep the cab company alive together."),
    B("vicky-donor", "Vicky Donor", 2012, 7.4, "Comedy/Drama",
      "A jobless Delhi boy becomes a serial sperm donor for a Punjabi-Bengali fertility clinic.",
      "Vicky's wife forgives him after learning the truth; the couple adopts one of the children he 'gifted'."),
    B("mimi", "Mimi", 2021, 7.6, "Comedy/Drama",
      "A small-town aspiring actress agrees to be a surrogate for a foreign couple — and is then abandoned.",
      "Mimi raises Raj as her own; the bio parents return, but the boy chooses Mimi as his family."),
    B("jolly-llb", "Jolly LLB", 2013, 7.9, "Drama/Comedy",
      "A Meerut lawyer takes up a high-profile hit-and-run PIL against a celebrity son in Delhi.",
      "Jolly forces the spoilt heir to plead guilty; the rich father is also implicated."),
    B("jolly-llb-2", "Jolly LLB 2", 2017, 7.4, "Drama/Comedy",
      "A Lucknow lawyer redeems himself by exposing a fake encounter that killed an innocent expectant father.",
      "The corrupt cop is convicted; the encounter victim's widow gets justice and a son's name."),
    B("dangal", "Dangal", 2016, 8.4, "Sports/Biopic",
      "A failed wrestler trains his daughters Geeta and Babita to wrestle at the international level.",
      "Geeta wins gold at the 2010 Commonwealth Games — her father, locked in a room by the coach, hears the anthem."),
    B("sultan", "Sultan", 2016, 7.0, "Sports/Drama",
      "A Haryanvi pehelwan rises, falls, and returns to MMA cages to win back his estranged wife.",
      "Sultan wins the championship; Aarfa accepts him back at ringside with their living son."),
    B("bajrangi-bhaijaan", "Bajrangi Bhaijaan", 2015, 8.0, "Drama",
      "A devout Indian man takes a mute Pakistani girl back across the border to her village.",
      "Pawan crosses the border on foot among hundreds of cheering people; Munni shouts 'Mama!' in his ear, healed."),
    B("padosan", "Padosan", 1968, 8.1, "Comedy/Romance",
      "A bumbling village simpleton enlists his theatre friends to woo the girl-next-door away from her music teacher.",
      "Bhola wins Bindu's hand by lip-syncing to Kishore's voice; Master-ji concedes graciously."),
    B("anand", "Anand", 1971, 8.4, "Drama",
      "A cancer patient determined to live joyfully changes the life of his cynical doctor.",
      "Anand dies smiling; a tape of his voice plays at his memorial — the Babumoshai he taught how to laugh."),
    B("guide", "Guide", 1965, 8.1, "Drama/Romance",
      "A tour guide turned reluctant saint fasts for rain in a drought-ridden village.",
      "Raju dies during the fast as the rains finally arrive — saint and sinner at once."),
    B("pakeezah", "Pakeezah", 1972, 7.9, "Romance/Drama",
      "A courtesan dreams of escaping her gilded cage when a stranger leaves her a love letter on a moving train.",
      "Sahibjaan is married off to the man who wrote the letter; she dances at the wedding and collapses."),
    B("amar-akbar-anthony", "Amar Akbar Anthony", 1977, 7.8, "Comedy/Action",
      "Three brothers separated in childhood are raised Hindu, Muslim and Christian, and reunite as adults.",
      "All three save their dying mother with a triple blood transfusion; villains are crushed in a final brawl."),
    B("don-1978", "Don", 1978, 7.7, "Action/Crime",
      "A police informant doubles as a slain Mumbai don to bust an international drug ring.",
      "Vijay kills DSP D'Silva's killer and clears his name; the diary nails the cartel."),
    B("zanjeer", "Zanjeer", 1973, 7.9, "Action",
      "A driven cop hunts the killer of his parents in a smuggling racket.",
      "Vijay strangles Teja with the very chain he wore as a child; the haunting nightmare ends."),
    B("deewar", "Deewar", 1975, 8.0, "Crime/Drama",
      "Two brothers — a smuggler and a cop — confront each other after a lifetime of class injustice.",
      "Vijay dies in his mother's lap on the temple steps; Ravi salutes."),
    B("mughal-e-azam", "Mughal-E-Azam", 1960, 8.1, "Romance/Drama",
      "A Mughal prince's love for a court dancer triggers a clash with his emperor father.",
      "Anarkali is sealed alive in a wall; the historical record is rewritten to spare Salim."),
    B("don-bhai", "Sholay (rerelease)", 1975, 8.1, "Action",
      "Two crooks are hired to capture a sadistic dacoit in Ramgarh.",
      "Veeru and Basanti ride away; Jai dies in Veeru's arms after blowing up the bridge."),
    B("don-iconic", "Mr. India", 1987, 8.0, "Sci-Fi/Action",
      "A poor violinist gets an invisibility device left by his scientist father and takes on Mogambo.",
      "Mr. India destroys Mogambo's island base — 'Mogambo khush hua' becomes his last words."),
    B("hum-aapke-hain-koun", "Hum Aapke Hain Koun..!", 1994, 7.5, "Family/Romance",
      "Two affectionate Delhi-Bombay families navigate weddings, loss and reunions across one season.",
      "Prem marries Nisha after his sister-in-law's death is mourned and life resumes."),
    B("hum-saath-saath-hain", "Hum Saath-Saath Hain", 1999, 6.0, "Family",
      "A modern Ramayana set in a wealthy joint-family business.",
      "The brothers reunite around their mother and the eldest is reinstated as heir."),
    B("vivah", "Vivah", 2006, 6.9, "Romance",
      "An arranged-match couple bond through letters as the wedding nears, until tragedy strikes.",
      "Burnt in a fire on her wedding eve, Poonam is married to Prem in the hospital — they walk into life together."),
    B("ghajini", "Ghajini", 2008, 7.2, "Action/Thriller",
      "A Mumbai businessman with anterograde amnesia hunts the men who murdered his girlfriend.",
      "Sanjay kills Ghajini in the asylum after one final tattooed reminder; he is institutionalised, cared for."),
    B("krrish", "Krrish", 2006, 6.4, "Sci-Fi/Action",
      "A super-powered village boy learns of his missing scientist father and adopts a masked vigilante identity.",
      "Krrish frees his father and defeats Dr Arya in Singapore; he returns to his Himalayan home."),
    B("krrish-3", "Krrish 3", 2013, 5.5, "Sci-Fi/Action",
      "Krrish protects Mumbai from a wheelchair-bound mutant warlord and his shape-shifting army.",
      "Krrish defeats Kaal; his cloned 'son' is given Kaya's heart and accepted as family."),
    B("ra-one", "Ra.One", 2011, 4.7, "Sci-Fi/Action",
      "A video-game villain breaks into reality and hunts the family of his creator.",
      "G.One sacrifices himself to delete Ra.One; his hologram returns to comfort the boy."),
    B("robot", "Robot (Endhiran)", 2010, 7.0, "Sci-Fi/Action",
      "An advanced humanoid robot's emotion chip turns him against his creator.",
      "Chitti is dismantled; a museum displays him 'because he can think' — a quiet warning."),
    B("ek-tha-tiger", "Ek Tha Tiger", 2012, 6.0, "Action/Romance",
      "A RAW agent falls in love with a Pakistani ISI agent on a Dublin mission.",
      "Tiger and Zoya disappear together — neither RAW nor ISI can find them."),
    B("tiger-zinda-hai", "Tiger Zinda Hai", 2017, 5.9, "Action",
      "Tiger leads a joint Indo-Pak op to rescue nurses kidnapped by an ISIS-like group in Iraq.",
      "All hostages are freed; Tiger is presumed dead but reappears with Zoya in the Alps."),
    B("war", "War", 2019, 6.5, "Action/Spy",
      "A RAW agent goes rogue; his protégé is sent to hunt him.",
      "It's revealed Kabir is undercover; he and Khalid kill the real traitor and disappear together."),
    B("pathaan", "Pathaan", 2023, 5.9, "Action/Spy",
      "An exiled RAW agent returns to stop a rogue ex-RAW operative from unleashing a smallpox bioweapon.",
      "Pathaan and Tiger team up; Jim is killed in the air-drop finale."),
    B("dunki", "Dunki", 2023, 6.4, "Comedy/Drama",
      "Four small-town friends take the donkey route to London chasing dreams.",
      "Decades later, they take Manu's last wish — to die in Punjab — back illegally over the border, this time as old men."),
    B("pk", "PK", 2014, 8.1, "Comedy/Drama",
      "A stranded alien innocently questions India's religious middlemen on TV.",
      "PK exposes the fake godman Tapasvi; he leaves Earth with a recorder full of human prayer-tapes."),
    B("munna-bhai-mbbs", "Munna Bhai MBBS", 2003, 8.1, "Comedy/Drama",
      "A small-time goon impersonates a doctor to live up to his father's pride.",
      "Munna is exposed but heals patients with 'jaadu ki jhappi'; he marries Suman and reforms the dean's family."),
    B("lage-raho-munna-bhai", "Lage Raho Munna Bhai", 2006, 8.1, "Comedy/Drama",
      "A goon hallucinates Mahatma Gandhi who teaches him 'Gandhigiri' to win a radio jockey's heart.",
      "Munna lives Gandhigiri on air; the corrupt builder confesses, the listeners are won over, Jhanvi accepts him."),
    B("3-idiots-redux", "Phir Hera Pheri", 2006, 7.0, "Comedy",
      "Three friends fall for a Ponzi scheme and have to recover the money before the kingpin kills them.",
      "Babu Bhaiya, Raju and Shyam stumble into the kidnapping plot, accidentally rescue the girl and become rich."),
    B("welcome", "Welcome", 2007, 7.0, "Comedy",
      "A respectable boy must marry a gangster's sister; chaos ensues across two Don families.",
      "Both dons agree to retire; Rajiv marries Sanjana and Uday accepts him as family."),
    B("hera-pheri", "Hera Pheri", 2000, 8.2, "Comedy",
      "Three Mumbai roommates accidentally intercept a kidnapping ransom call and try to scam their way to crores.",
      "After many disasters they hand the money to the police and split a small reward — but the gold-coin scam is set up for the sequel."),
    B("golmaal", "Golmaal: Fun Unlimited", 2006, 7.6, "Comedy",
      "Four conmen pretend to be the long-lost grandsons of a blind couple living in a beach bungalow.",
      "The real grandson returns; the boys are caught but accepted by the loving couple."),
    B("housefull", "Housefull", 2010, 5.5, "Comedy",
      "A perpetually unlucky man tries to fake a marriage in London and ends up in a tangle of identities.",
      "All couples are sorted out at a multi-wedding finale; Aarush gets his real bride."),
    B("hum-tum", "Hum Tum", 2004, 7.1, "Romance/Comedy",
      "A cartoonist and a serious girl keep crossing paths over a decade across continents.",
      "After her widowhood, Karan and Rhea finally marry — twelve years after the plane ride."),
    B("kal-ho-naa-ho", "Kal Ho Naa Ho", 2003, 7.9, "Romance/Drama",
      "A New York girl is romanced by a charming neighbor who hides his terminal illness.",
      "Aman dies; Naina marries Rohit; Aman watches from the heavens with a smile."),
    B("veer-zaara", "Veer-Zaara", 2004, 7.7, "Romance/Drama",
      "An Indian Air Force officer spends 22 years in a Pakistani jail to protect the woman he loves.",
      "A young Pakistani lawyer wins his freedom; Veer reunites with Zaara on Indian soil."),
    B("chak-de-india", "Chak De! India", 2007, 8.2, "Sports/Drama",
      "A disgraced ex-captain coaches the Indian women's hockey team to redeem himself and them.",
      "India wins the World Cup; Kabir's name is restored on the honour board."),
    B("iqbal", "Iqbal", 2005, 8.1, "Sports/Drama",
      "A deaf-mute village boy fights every odd to play cricket for India.",
      "Iqbal takes five wickets in a Ranji match and earns the India cap his sister never thought she'd see."),
    B("paan-singh-tomar", "Paan Singh Tomar", 2010, 8.2, "Biopic/Drama",
      "An army athlete-turned-medal-winner becomes a Chambal rebel after the system fails him.",
      "Paan Singh is gunned down by police; the closing scrolls his stadium records."),
    B("the-dirty-picture", "The Dirty Picture", 2011, 6.9, "Biopic/Drama",
      "A South Indian B-grade siren rises and falls in 1980s film industry.",
      "Silk dies of an overdose, leaving a note thanking Ramakant for the only real love she knew."),
    B("ankhon-dekhi", "Ankhon Dekhi", 2013, 8.2, "Drama",
      "A middle-aged Old Delhi clerk decides to believe only what he sees with his own eyes.",
      "Bauji jumps off a hill to test his belief that flight is possible if he wills it; he dies, free at last."),
    B("masoom", "Masoom", 1983, 8.4, "Drama",
      "An architect's wife meets the illegitimate son she never knew about.",
      "Indu accepts the boy at the airport gate; the family chooses to start over together."),
    B("salaam-bombay", "Salaam Bombay!", 1988, 7.9, "Drama",
      "A small-town runaway boy survives Mumbai's red-light district as a tea-boy.",
      "Krishna kills Baba; the police take everyone away; Krishna sits alone, spinning a top under a streetlight."),
    B("dil-se", "Dil Se..", 1998, 7.7, "Romance/Thriller",
      "An All India Radio reporter falls for an enigmatic woman who is in fact a militant suicide bomber.",
      "Amar embraces Meghna in Delhi just as her vest detonates — they die together."),
    B("delhi-6", "Delhi-6", 2009, 6.6, "Drama",
      "A young NRI returns with his ailing grandmother to old Delhi and witnesses Hindu-Muslim tension catalysed by a 'kala bandar' rumor.",
      "Roshan is shot trying to stop a riot; his grandmother's wish to die in Chandni Chowk is fulfilled."),
    B("rang-rasiya", "Rang Rasiya", 2008, 7.5, "Biopic/Drama",
      "Painter Raja Ravi Varma fights blasphemy charges for portraying Hindu goddesses on litho-print.",
      "He wins the trial after a fiery courtroom defence; his lithographs democratize Hindu iconography."),
    B("sadma", "Sadma", 1983, 8.3, "Drama",
      "A Bangalore teacher rescues an amnesiac girl from a brothel and cares for her until her memory returns.",
      "Once cured, Nehalata fails to recognise Somu as he chases her train, banging the window — he is left alone."),
    B("astitva", "Astitva", 2000, 7.6, "Drama",
      "A wife confesses a one-time affair from twenty years ago; her son turns out to be its product.",
      "Aditi walks out of her hypocritical husband's home, choosing dignity over the comfortable cage."),
    B("water", "Water", 2005, 7.7, "Drama",
      "An eight-year-old widow and a young one find love and hope in 1938 Banaras.",
      "Shakuntala puts Chuyia on Gandhi's train under Narayan's care, choosing the girl's future over her ashram."),
    B("kal-ki-aawaz", "Hindustan Ki Kasam", 1973, 6.5, "War/Drama",
      "An Indian Air Force officer leads a special op during the 1971 war.",
      "The squadron destroys the Pakistani radar; the officer survives to see the surrender at Dhaka."),
    B("border", "Border", 1997, 7.9, "War/Drama",
      "Indian troops at Longewala defend a forward post against an entire armoured Pakistani brigade.",
      "Major Chandpuri's men hold till dawn; the Indian Air Force decimates the tanks at first light."),
    B("lakshya", "Lakshya", 2004, 8.0, "War/Drama",
      "A directionless rich Delhi boy joins the army and finds purpose at Kargil.",
      "Captain Karan Shergill leads the assault on a Tiger Hill peak; the post is captured and the war won."),
    B("the-tashkent-files", "The Tashkent Files", 2019, 7.5, "Mystery/Drama",
      "A young journalist is tasked with investigating Lal Bahadur Shastri's mysterious 1966 death.",
      "The committee delivers a split report; the journalist is offered hush money and ascends, ambiguous."),
    B("shaitaan", "Shaitaan", 2024, 7.0, "Thriller/Horror",
      "A man holds a family hostage by hypnotising the daughter at their farmhouse.",
      "The father uses an old guru's amulet to break the spell; the cult-leader is killed in the basement ritual."),
    B("animal", "Animal", 2023, 6.5, "Action/Crime",
      "A neglected son turns into a violent enforcer after an attempt on his industrialist father's life.",
      "Ranvijay slaughters the half-brother conspirators in a mansion massacre; reconciles, briefly, with his father."),
    B("12th-fail", "12th Fail", 2023, 9.1, "Biopic/Drama",
      "An aspirant from rural Chambal cracks the UPSC after dropping out and starting from scratch.",
      "Manoj clears the IPS interview; he is posted as DSP, vindicating his family and Pritam Pandey."),
    B("gully-boy-2", "Sairat", 2016, 8.5, "Romance/Drama",
      "A Maratha-cricketer boy and an upper-caste girl elope in defiance of village honour codes.",
      "Years later, after a child, both are murdered by the girl's family in their Hyderabad home — the toddler walks out alone in blood."),
    B("oh-my-god", "OMG: Oh My God!", 2012, 8.1, "Comedy/Drama",
      "An atheist shopkeeper sues god after his shop is destroyed in an earthquake.",
      "Krishna himself helps him win in court; the godmen are exposed and people pray to Kanji's idol — which he rejects."),
    B("oh-my-god-2", "OMG 2", 2023, 8.1, "Drama",
      "A Shiva devotee sues the school system over the moral panic that drove his son to attempt suicide.",
      "Kanti wins the right for proper sex education in schools, citing scriptures themselves."),
    B("zwigato", "Zwigato", 2022, 7.4, "Drama",
      "A laid-off factory worker delivers food on a gig app and slowly drowns under five-star ratings.",
      "Manas walks out of a humiliating delivery; his wife, now earning, supports their family while he reconsiders dignity."),
    B("kantara", "Kantara", 2022, 8.4, "Action/Folklore",
      "A village forest officer clashes with a cocky kambala star over land rights, against a backdrop of Daiva worship.",
      "Shiva is possessed by the deity Panjurli; he kills the corrupt landlord and restores the village's land."),
    B("salaar", "Salaar", 2023, 6.6, "Action",
      "A loyal enforcer is reactivated to protect his childhood friend's bid to rule the city of Khansaar.",
      "Deva crowns Vardha, slaughters the council and reveals himself the true heir — to be continued."),
    B("jawan", "Jawan", 2023, 7.0, "Action/Drama",
      "A jail warden masterminds vigilante hostage stunts to expose corporate-political corruption.",
      "Vikram's son Azad finishes his father's mission, killing arms dealer Kalee on a Russian island."),
    B("rocky-aur-rani-kii-prem-kahaani", "Rocky Aur Rani Kii Prem Kahaani", 2023, 6.2, "Romance/Comedy",
      "A flashy Punjabi boy and a sharp Bengali journalist swap households to win their elders' approval.",
      "Both families let go of their prejudices; Rocky and Rani marry on a Kolkata stage."),
    B("brahmastra", "Brahmastra Part One: Shiva", 2022, 5.6, "Fantasy/Action",
      "A Mumbai DJ discovers he wields the fire-Astra and joins a secret society of celestial weapons.",
      "Shiva rebirths the Brahmastra by uniting all three pieces; his villainous mother-figure is destroyed."),
    B("the-kashmir-files", "The Kashmir Files", 2022, 8.2, "Drama",
      "A Kashmiri Pandit student traces the truth of his family's 1990 exodus.",
      "Krishna delivers a JNU monologue exposing the genocide; he reconciles with his roots."),
    B("the-kerala-story", "The Kerala Story", 2023, 7.4, "Drama",
      "Three Kerala nursing students are radicalised and trafficked to ISIS in Syria.",
      "Shalini is captured by allied forces in Afghanistan, surviving but stateless; her testimony reaches Indian media."),
    B("83", "83", 2021, 7.5, "Sports/Biopic",
      "Kapil Dev's underdog Indian squad's path to the 1983 Cricket World Cup.",
      "India beats West Indies in the Lord's final; Kapil lifts the cup as the world watches."),
    B("ms-dhoni-the-untold-story", "M.S. Dhoni: The Untold Story", 2016, 7.9, "Sports/Biopic",
      "A Ranchi ticket-collector's rise from town cricket to India captaincy.",
      "Dhoni hits the winning six in the 2011 World Cup final at Wankhede."),
    B("airlift", "Airlift", 2016, 7.9, "Drama",
      "An Indian businessman in Kuwait organises the largest civilian evacuation in history during the 1990 invasion.",
      "All 170,000 Indians are flown home; Ranjit is honoured by the Indian government."),
    B("neerja", "Neerja", 2016, 7.7, "Biopic/Drama",
      "Pan Am flight purser Neerja Bhanot stares down hijackers in Karachi to save 359 passengers.",
      "Neerja is shot shielding three children; she is awarded the Ashoka Chakra posthumously."),
    B("raazi", "Raazi", 2018, 7.7, "Spy/Drama",
      "A young Kashmiri girl is married into a Pakistani military family as an Indian spy before the 1971 war.",
      "Sehmat's intel saves the INS Vikrant; she returns to India, raising her son alone."),
    B("hrithik-gold", "Gold", 2018, 6.6, "Sports/Drama",
      "An assistant manager rebuilds an Indian hockey team for the first post-Independence Olympic gold.",
      "India wins the 1948 London gold against Britain; the new tricolour is hoisted at Wembley."),
    B("wake-up-sid", "Wake Up Sid", 2009, 7.5, "Comedy/Drama",
      "A spoilt Mumbai college boy moves out and slowly grows up alongside an older friend-flatmate.",
      "Sid has his first photo published; he and Aisha kiss on her terrace at sunrise."),
    B("luck-by-chance", "Luck By Chance", 2009, 7.5, "Drama",
      "A struggling actor breaks into Bollywood by exploiting an industry insider's daughter.",
      "Vikram becomes a star but loses Sona; she walks past him on a film set, unaffected, finally a heroine herself."),
    B("kapoor-and-sons", "Kapoor & Sons", 2016, 7.7, "Family/Drama",
      "Two brothers come home to a fracturing family in Coonoor and uncover affairs, secrets and a closet.",
      "After Dadu's death the family forgives each other; Rahul reveals he is gay and is accepted."),
    B("dear-zindagi", "Dear Zindagi", 2016, 7.3, "Drama",
      "A young Mumbai cinematographer in Goa works through her childhood through unconventional therapy.",
      "Kaira reconciles with her parents and her own future, sets boundaries and starts her own path."),
    B("zindagi-na-milegi-dobara", "Zindagi Na Milegi Dobara", 2011, 8.1, "Drama/Adventure",
      "Three friends on a Spain bachelor trip face their fears of love, depth and skydiving.",
      "Each friend confronts a fear; Arjun lets go of money, Kabir of an unwanted marriage, Imran finds his bio dad."),
    B("dor", "Dor", 2006, 8.1, "Drama",
      "A Rajasthani widow's life depends on a Muslim woman from Himachal whose husband her own husband killed.",
      "Meera signs the forgiveness papers; both women return home, free of vengeance."),
    B("astha", "Aastha: In the Prison of Spring", 1997, 6.9, "Drama",
      "A middle-class Mumbai homemaker drifts into prostitution; her husband finds out.",
      "Mansi confesses and quits; Amar forgives her; their marriage survives, scarred and humbled."),
    B("ardh-satya", "Ardh Satya", 1983, 8.6, "Crime/Drama",
      "An honest Bombay sub-inspector is crushed between corrupt politicians, bosses and his abusive father.",
      "Anant strangles a corrupt councillor and surrenders, finally on his own moral terms."),
    B("nayakan", "Nayakan", 1987, 8.6, "Crime/Drama",
      "A Tamil migrant becomes Bombay's underworld 'godfather' protecting his Dharavi people.",
      "Velu is killed by his estranged grandson on the temple steps where it all began."),
    B("kaala", "Kaala", 2018, 7.0, "Action/Drama",
      "A Dharavi don fights a Hindutva politician for slum land rights.",
      "Kaala is reborn in revolution — black, blue and red splash the city as the people rise after his fall."),
]

# ---------------- Hollywood movies (deeper, ~80 more) ----------------
NEW += [
    H("the-matrix", "The Matrix", 1999, 8.7, "Sci-Fi/Action",
      "A hacker discovers reality is a simulation and joins a rebellion.",
      "Neo accepts his role as The One, breaks Agent Smith and promises the system a coming revolution."),
    H("the-matrix-reloaded", "The Matrix Reloaded", 2003, 7.2, "Sci-Fi/Action",
      "Neo, Trinity and Morpheus race to save Zion from 250,000 Sentinels.",
      "Neo learns he's part of a sixth iteration of The One; Bane is possessed by Smith."),
    H("the-matrix-revolutions", "The Matrix Revolutions", 2003, 6.7, "Sci-Fi/Action",
      "Neo strikes a truce with the Machines to defeat Smith.",
      "Neo neutralises Smith inside the Matrix at the cost of his life; Zion is saved."),
    H("interstellar", "Interstellar", 2014, 8.7, "Sci-Fi/Drama",
      "A widowed pilot leads a wormhole mission to find humanity a new home.",
      "Cooper sends quantum data through a tesseract from inside a black hole; Murph cracks the equation and rescues humanity."),
    H("dunkirk", "Dunkirk", 2017, 7.8, "War/Drama",
      "Allied troops trapped on a French beach evacuate via three intersecting timelines.",
      "Civilian boats ferry hundreds of thousands across the Channel; Mr. Dawson keeps going."),
    H("oppenheimer", "Oppenheimer", 2023, 8.3, "Biopic/Drama",
      "The father of the atomic bomb is celebrated and then politically destroyed.",
      "Oppenheimer's clearance is revoked at a kangaroo hearing; decades later he is rehabilitated, but the chain reaction has already begun."),
    H("tenet", "Tenet", 2020, 7.3, "Sci-Fi/Action",
      "A CIA agent learns to manipulate time-inverted bullets to stop World War III.",
      "The Protagonist seals a 'temporal pincer' op in Stalsk-12, foiling Sator's reverse algorithm."),
    H("memento", "Memento", 2000, 8.4, "Thriller",
      "A man with anterograde amnesia hunts his wife's killer with tattoos and Polaroids.",
      "Leonard reveals he's choosing to forget that he killed the real attacker years ago — and lies to his future self again."),
    H("the-prestige", "The Prestige", 2006, 8.5, "Mystery/Drama",
      "Two rival magicians in Victorian London push obsession to its limit.",
      "Borden's twin brother is hanged; Angier's clones are revealed in a basement of dead duplicates."),
    H("fight-club", "Fight Club", 1999, 8.8, "Drama",
      "An insomniac office worker forms an underground fight club with a soap salesman.",
      "Tyler is the narrator's hallucination; he shoots himself to kill Tyler and watches as Project Mayhem detonates the city."),
    H("seven", "Se7en", 1995, 8.6, "Crime/Thriller",
      "Two detectives chase a serial killer staging the seven deadly sins.",
      "John Doe presents Mills with his wife's head; Mills shoots him in rage, completing 'wrath'."),
    H("the-silence-of-the-lambs", "The Silence of the Lambs", 1991, 8.6, "Thriller",
      "A young FBI trainee consults Hannibal Lecter to catch Buffalo Bill.",
      "Clarice kills Bill in his basement; Hannibal escapes prison and calls Clarice to wish her well."),
    H("schindlers-list", "Schindler's List", 1993, 9.0, "Biopic/Drama",
      "A Nazi industrialist saves a thousand Jewish workers via his enamelware factory.",
      "Schindler weeps for not saving more; survivors place stones on his grave in Jerusalem."),
    H("saving-private-ryan", "Saving Private Ryan", 1998, 8.6, "War",
      "A WWII squad braves Normandy to bring home a paratrooper after his brothers' deaths.",
      "Captain Miller dies on the Ramelle bridge; Ryan, decades later, asks his wife if he 'earned it'."),
    H("titanic", "Titanic", 1997, 7.9, "Romance/Drama",
      "A poor artist and a first-class girl fall in love on the doomed RMS Titanic.",
      "Jack freezes in the Atlantic; Old Rose drops the Heart of the Ocean into the sea and joins him in dreams."),
    H("avatar", "Avatar", 2009, 7.9, "Sci-Fi/Action",
      "A paraplegic Marine bonds with a Na'vi tribe on Pandora.",
      "Jake's consciousness is permanently transferred to his Na'vi body; the Na'vi expel the humans."),
    H("avatar-the-way-of-water", "Avatar: The Way of Water", 2022, 7.6, "Sci-Fi/Action",
      "Jake Sully's family flees to the reef-clan Metkayina to escape a returning RDA.",
      "Quaritch is defeated; Neteyam dies; the Sullys are accepted by the reef people."),
    H("gladiator", "Gladiator", 2000, 8.5, "Action/Drama",
      "A betrayed Roman general becomes a slave-gladiator who works his way up to a Colosseum showdown with the Emperor.",
      "Maximus kills Commodus and dies in the arena; he sees his murdered family in Elysium."),
    H("braveheart", "Braveheart", 1995, 8.4, "Drama/War",
      "William Wallace leads Scotland in revolt against Edward I of England.",
      "Wallace is hanged, drawn and quartered after one last shout of 'Freedom!'; Robert the Bruce wins independence at Bannockburn."),
    H("lord-of-the-rings-fellowship", "The Lord of the Rings: The Fellowship of the Ring", 2001, 8.9, "Fantasy/Adventure",
      "Nine companions set out to destroy the One Ring in Mordor.",
      "Boromir dies defending the hobbits; the Fellowship breaks; Frodo and Sam continue alone."),
    H("lord-of-the-rings-two-towers", "The Lord of the Rings: The Two Towers", 2002, 8.8, "Fantasy/Adventure",
      "The remaining members fight separate wars while Frodo nears Mordor.",
      "Helm's Deep stands; Rohan rides to Gondor; Gollum plots Frodo's death."),
    H("lord-of-the-rings-return-of-the-king", "The Lord of the Rings: The Return of the King", 2003, 9.0, "Fantasy/Adventure",
      "Frodo reaches Mount Doom while Aragorn rides to claim his throne.",
      "Frodo and Gollum struggle on Mount Doom; the Ring is destroyed; Aragorn is crowned King; Frodo sails to the Grey Havens."),
    H("the-hobbit", "The Hobbit: An Unexpected Journey", 2012, 7.8, "Fantasy/Adventure",
      "Bilbo Baggins joins thirteen dwarves to reclaim Erebor from Smaug.",
      "Bilbo finds the Ring in Gollum's cave; the company reaches Erebor as Smaug awakens."),
    H("star-wars-a-new-hope", "Star Wars: A New Hope", 1977, 8.6, "Sci-Fi/Adventure",
      "A farm boy joins a Rebellion to destroy the Death Star.",
      "Luke fires the proton torpedo down the exhaust port; the Death Star explodes, the Rebellion is celebrated."),
    H("the-empire-strikes-back", "The Empire Strikes Back", 1980, 8.7, "Sci-Fi/Adventure",
      "The Rebel Alliance is hunted across the galaxy as Luke trains under Yoda.",
      "Vader reveals he is Luke's father; Han is frozen in carbonite and taken to Jabba."),
    H("return-of-the-jedi", "Return of the Jedi", 1983, 8.3, "Sci-Fi/Adventure",
      "The Rebels rescue Han and assault the second Death Star.",
      "Vader saves Luke and destroys the Emperor; the Empire falls; Yoda, Obi-Wan and Anakin watch the Ewok celebration."),
    H("the-force-awakens", "Star Wars: The Force Awakens", 2015, 7.8, "Sci-Fi/Adventure",
      "A scavenger and a defector spark a Resistance against the First Order.",
      "Rey finds Luke on Ahch-To and offers him his old lightsaber."),
    H("rogue-one", "Rogue One: A Star Wars Story", 2016, 7.8, "Sci-Fi/Adventure",
      "A Rebel team steals the Death Star plans.",
      "All members die transmitting the plans to Princess Leia just before A New Hope begins."),
    H("the-mandalorian-movie-tropes", "The Mandalorian (Season 1)", 2019, 8.7, "Sci-Fi/Adventure",
      "A bounty hunter protects a Force-sensitive child from Imperial remnants.",
      "Mando defeats Moff Gideon and becomes The Child's official guardian under Mandalorian creed."),
    H("indiana-jones-raiders", "Raiders of the Lost Ark", 1981, 8.4, "Adventure",
      "Indy races the Nazis to the Ark of the Covenant.",
      "The Ark melts the Nazis; the US government locks it in a warehouse."),
    H("jurassic-park", "Jurassic Park", 1993, 8.2, "Sci-Fi/Adventure",
      "A theme park of cloned dinosaurs goes catastrophically wrong on opening weekend.",
      "Grant, Sattler and the Murphy kids escape by helicopter as the T-Rex saves them from raptors."),
    H("e-t", "E.T. the Extra-Terrestrial", 1982, 7.9, "Sci-Fi/Family",
      "A boy hides a stranded alien in his California suburb.",
      "Elliott helps E.T. phone home; the spaceship returns and they part with the words 'I'll be right here'."),
    H("back-to-the-future", "Back to the Future", 1985, 8.5, "Sci-Fi/Comedy",
      "A teen accidentally travels to 1955 in a DeLorean and must get his parents to fall in love.",
      "Marty returns to a better 1985; Doc arrives in a flying car asking him to come to the future."),
    H("the-truman-show", "The Truman Show", 1998, 8.2, "Drama/Comedy",
      "A man slowly realises his entire life is a 24/7 TV show.",
      "Truman walks through the painted-sky exit door, says his goodbye line and leaves the studio."),
    H("the-sixth-sense", "The Sixth Sense", 1999, 8.2, "Mystery/Drama",
      "A child psychologist treats a boy who claims to see dead people.",
      "Crowe realises he himself has been dead since the opening scene; he says goodbye to his wife and crosses over."),
    H("good-will-hunting", "Good Will Hunting", 1997, 8.3, "Drama",
      "A South Boston janitor turns out to be a math genius and is mentored by a grieving therapist.",
      "Will leaves a note 'had to go see about a girl' and drives west to find Skylar in California."),
    H("a-beautiful-mind", "A Beautiful Mind", 2001, 8.2, "Biopic/Drama",
      "Mathematician John Nash's hallucinations and Nobel Prize.",
      "Nash accepts his Nobel and ignores the hallucinations he's lived with for decades."),
    H("the-king-s-speech", "The King's Speech", 2010, 8.0, "Biopic/Drama",
      "King George VI overcomes a stammer with the help of an unconventional therapist.",
      "He delivers the 1939 wartime radio speech without faltering; he and Logue remain lifelong friends."),
    H("12-years-a-slave", "12 Years a Slave", 2013, 8.1, "Biopic/Drama",
      "A free black man is kidnapped and sold into Louisiana slavery.",
      "Solomon is finally rescued and reunited with his family in Saratoga, twelve years after."),
    H("the-departed", "The Departed", 2006, 8.5, "Crime/Thriller",
      "A cop infiltrates the Boston Irish mob while a mole infiltrates the police.",
      "Costigan is shot in an elevator; Sullivan is killed at his apartment by a fellow cop; the rat scurries past at the end."),
    H("inglourious-basterds", "Inglourious Basterds", 2009, 8.3, "War/Drama",
      "A Jewish-American squad and a French theatre owner conspire to kill Hitler.",
      "Hitler and the Nazi high command burn alive in Shoshanna's Paris cinema; Aldo carves a swastika on Landa's forehead."),
    H("django-unchained", "Django Unchained", 2012, 8.5, "Western",
      "A freed slave teams with a bounty hunter to rescue his wife from a Mississippi plantation.",
      "Django destroys Candyland with dynamite, kills the overseers and rides off with Broomhilda."),
    H("once-upon-a-time-in-hollywood", "Once Upon a Time in Hollywood", 2019, 7.6, "Drama",
      "A fading TV star and his stunt double drift through 1969 Los Angeles.",
      "Cliff and Rick repel the Manson family; Sharon Tate lives, inviting Rick over for a drink."),
    H("kill-bill-vol-1", "Kill Bill: Vol. 1", 2003, 8.2, "Action",
      "A bride awakens from a coma to murder her former assassination squad.",
      "The Bride defeats O-Ren on a snowy Tokyo garden; she is told her daughter is alive."),
    H("kill-bill-vol-2", "Kill Bill: Vol. 2", 2004, 8.0, "Action",
      "She finishes the rest of the squad and finally meets Bill.",
      "The Bride uses the Five-Point-Palm Exploding-Heart Technique on Bill and reunites with her daughter B.B."),
    H("la-la-land", "La La Land", 2016, 8.0, "Romance/Musical",
      "A jazz pianist and an aspiring actress fall in love in Los Angeles.",
      "Years later they meet at his club; share an alternate-life montage and a wistful nod, then go their separate ways."),
    H("whiplash", "Whiplash", 2014, 8.5, "Drama/Music",
      "A young drummer is broken and remade by a sadistic conservatory teacher.",
      "Andrew nails the 'Caravan' solo at JVC; Fletcher locks eyes with him in approval — applause."),
    H("birdman", "Birdman", 2014, 7.7, "Drama",
      "A washed-up superhero actor stages a Broadway play in a desperate bid for relevance.",
      "Riggan shoots himself onstage but survives; he jumps from a window — his daughter looks up and smiles."),
    H("parasite-en", "Parasite", 2019, 8.6, "Thriller/Drama",
      "A poor Korean family infiltrates a wealthy household one job at a time.",
      "After a basement double-murder, Ki-woo dreams of buying the house to free his father — a quiet Morse-code letter ends it all."),
    H("ratatouille", "Ratatouille", 2007, 8.1, "Animation/Family",
      "A rat with a refined palate cooks through a Parisian sous-chef.",
      "Anton Ego writes a glowing review; Gusteau's restaurant is closed but Linguini and Remy open a new bistro."),
    H("up", "Up", 2009, 8.3, "Animation/Family",
      "A widowed retiree flies his house to South America to honour his wife's dream.",
      "Carl helps Russell save Kevin and the dogs; he and the boy bond as adoptive grandfather and grandson."),
    H("wall-e", "WALL-E", 2008, 8.4, "Animation/Sci-Fi",
      "A trash-compactor robot on Earth meets EVE and follows her to space.",
      "Humanity returns to Earth on the Axiom; WALL-E and EVE plant the first sapling together."),
    H("toy-story", "Toy Story", 1995, 8.3, "Animation/Family",
      "A pull-string cowboy is jealous of a new spaceman toy.",
      "Woody and Buzz catch up to Andy's moving van together — friends, finally."),
    H("toy-story-3", "Toy Story 3", 2010, 8.3, "Animation/Family",
      "Andy's toys end up at a daycare ruled by a strawberry-scented bear.",
      "Andy gives the toys to Bonnie; Woody waves goodbye as the boy drives away to college."),
    H("finding-nemo", "Finding Nemo", 2003, 8.2, "Animation/Family",
      "A clownfish dad chases a Sydney-bound boat to rescue his son.",
      "Marlin and Dory free Nemo from the dentist; the reef is reunited and a little braver."),
    H("frozen", "Frozen", 2013, 7.4, "Animation/Family",
      "An ice-powered queen accidentally freezes her kingdom and her sister.",
      "Anna saves Elsa with an act of true love; Arendelle thaws and the sisters skate together."),
    H("encanto", "Encanto", 2021, 7.2, "Animation/Family",
      "A Colombian girl without magical powers must save her gifted family from cracking apart.",
      "Mirabel rebuilds the casita with the family; Abuela embraces her ungifted granddaughter."),
    H("the-lion-king", "The Lion King", 1994, 8.5, "Animation/Family",
      "A lion cub is exiled after his uncle frames him for his father's death.",
      "Simba defeats Scar at Pride Rock; he, Nala and the new heir are crowned."),
    H("aladdin", "Aladdin", 1992, 8.0, "Animation/Family",
      "A street thief becomes a prince to win Princess Jasmine.",
      "Aladdin frees the Genie; the Sultan changes the law and lets Jasmine marry whom she chooses."),
    H("beauty-and-the-beast", "Beauty and the Beast", 1991, 8.0, "Animation/Family",
      "A bookish girl falls for a cursed prince in his enchanted castle.",
      "Belle's love breaks the curse; Beast turns human and the castle is restored."),
    H("the-incredibles", "The Incredibles", 2004, 8.0, "Animation/Action",
      "A retired superhero family comes back to stop a fanboy-turned-villain.",
      "The family defeats Syndrome; the Incredibles are publicly licensed again."),
    H("spider-man-into-the-spider-verse", "Spider-Man: Into the Spider-Verse", 2018, 8.4, "Animation/Action",
      "Brooklyn teen Miles Morales joins Spider-people from across the multiverse.",
      "Miles defeats Kingpin, sends the others home and embraces being his world's Spider-Man."),
    H("spider-man-no-way-home", "Spider-Man: No Way Home", 2021, 8.2, "Action",
      "A spell to make people forget Peter Parker's identity opens the multiverse.",
      "Peter cures the villains and asks Doctor Strange to make everyone, including MJ and Ned, forget him."),
    H("avengers-endgame", "Avengers: Endgame", 2019, 8.4, "Action",
      "The remaining Avengers attempt a time-heist to undo Thanos's snap.",
      "Tony Stark snaps Thanos and his army into dust at the cost of his life; Cap returns the stones and grows old with Peggy."),
    H("the-batman", "The Batman", 2022, 7.8, "Action/Crime",
      "A second-year Batman hunts the Riddler through a corruption-rotted Gotham.",
      "Bruce reframes himself as a beacon of hope rather than vengeance; the Joker is glimpsed in Arkham."),
    H("joker", "Joker", 2019, 8.4, "Crime/Drama",
      "A failed stand-up comedian descends into the Joker as Gotham riots.",
      "Arthur is celebrated by the rioters atop a police car; in Arkham he leaves bloody footprints."),
    H("logan", "Logan", 2017, 8.1, "Action/Drama",
      "An aged Wolverine smuggles a young mutant girl across America.",
      "Logan dies saving Laura and the kids on the Canadian border; she places his cross sideways into an X."),
    H("deadpool", "Deadpool", 2016, 8.0, "Action/Comedy",
      "A mercenary becomes a wisecracking, immortal antihero hunting the man who tortured him.",
      "Wade carves Ajax with his own knife; he reunites with Vanessa, masked and disfigured."),
    H("guardians-of-the-galaxy", "Guardians of the Galaxy", 2014, 8.0, "Sci-Fi/Action",
      "A ragtag group of cosmic outlaws form an unlikely team.",
      "The Guardians stop Ronan; Quill keeps the Power Stone in a Nova Corps vault."),
    H("inside-out", "Inside Out", 2015, 8.1, "Animation/Family",
      "Five emotions inside a girl's mind navigate her family's move to San Francisco.",
      "Joy and Sadness rebuild Riley's core memories together; Riley reconciles with her parents."),
    H("coco", "Coco", 2017, 8.4, "Animation/Family",
      "A boy crosses into the Land of the Dead to find his musician ancestor.",
      "Miguel restores his great-great-grandfather's place in Mama Coco's memory; Hector survives in legend."),
    H("the-shape-of-water", "The Shape of Water", 2017, 7.3, "Romance/Fantasy",
      "A mute janitor falls for a captured amphibian creature in a Cold War lab.",
      "Elisa is shot but the creature heals her gills; they descend together into the water, alive."),
    H("everything-everywhere-all-at-once", "Everything Everywhere All at Once", 2022, 7.8, "Sci-Fi/Drama",
      "A laundromat owner is the only one who can stop a multiversal nemesis — her daughter.",
      "Evelyn embraces Joy across a googly-eye bagel; she chooses kindness over despair, and the family heals."),
    H("nomadland", "Nomadland", 2020, 7.3, "Drama",
      "A widow takes to the American West in a van after her town's gypsum plant closes.",
      "Fern returns to Empire one last time, says goodbye to the empty house, and drives off into the sunrise — alone but not lonely."),
    H("oppenheimer-related", "The Imitation Game", 2014, 8.0, "Biopic/Drama",
      "Alan Turing leads the codebreaking effort against Enigma at Bletchley Park.",
      "Turing breaks Enigma but is later prosecuted for being gay; he chemically-castrated, dies of cyanide poisoning."),
    H("ford-v-ferrari", "Ford v Ferrari", 2019, 8.1, "Drama/Sport",
      "Carroll Shelby and Ken Miles build a Ford to beat Ferrari at Le Mans 1966.",
      "Miles slows down at the finish for Ford's PR; another Ford wins by a nose; Miles dies in a test crash months later."),
    H("the-social-network", "The Social Network", 2010, 7.8, "Biopic/Drama",
      "Mark Zuckerberg's rise from Harvard dorm to a multibillion-dollar Facebook lawsuit.",
      "He sits in a deposition room refreshing Erica Albright's friend request — a billion users, alone."),
    H("the-wolf-of-wall-street", "The Wolf of Wall Street", 2013, 8.2, "Crime/Drama",
      "Penny-stock king Jordan Belfort's quaalude-fuelled rise and fall.",
      "Belfort gets a light sentence, betrays Donnie; afterwards he tours the world teaching sales."),
    H("the-revenant", "The Revenant", 2015, 8.0, "Adventure/Drama",
      "A frontiersman crawls 200 miles for revenge after a bear mauling and his son's murder.",
      "Hugh Glass kills Fitzgerald with help from the Arikara, then collapses in the snow as he sees his late wife."),
    H("mad-max-fury-road", "Mad Max: Fury Road", 2015, 8.1, "Action",
      "Across a post-apocalyptic desert, a war-rig driver smuggles five wives away from a tyrant.",
      "Furiosa kills Immortan Joe and rides his rig to the Citadel; the people are freed."),
    H("the-grand-budapest-hotel", "The Grand Budapest Hotel", 2014, 8.1, "Comedy/Drama",
      "A legendary hotel concierge is framed for the murder of an elderly aristocrat.",
      "Gustave clears his name, dies in a war years later; his lobby boy Zero inherits the hotel and remembers him."),
    H("knives-out", "Knives Out", 2019, 7.9, "Mystery/Comedy",
      "A detective investigates the suspicious death of a mystery novelist patriarch.",
      "Marta is the rightful heir; the murderer Ransom is arrested as Marta drinks coffee from a 'My House' mug."),
    H("glass-onion", "Glass Onion: A Knives Out Mystery", 2022, 7.1, "Mystery/Comedy",
      "A second whodunit on a billionaire's Greek island.",
      "Helen torches the Mona Lisa and the glass dome; Miles Bron's empire collapses in flames."),
]

# ---------------- Foreign / world TV (region=hollywood, kind=tv) ----------------
NEW += [
    TVF("the-wire", "The Wire", 2002, 9.3, "Crime/Drama",
        "Five seasons across drug corners, docks, schools and newspapers in Baltimore.",
        "McNulty's fake serial killer scam is buried; the city goes on, every actor replaced by a new Marlo, Daniels, Bubbles, Carcetti."),
    TVF("the-sopranos", "The Sopranos", 1999, 9.2, "Crime/Drama",
        "A New Jersey mob boss's anxiety attacks lead him to therapy.",
        "Tony eats onion rings with his family at Holsten's; the bell jingles, the screen cuts to black — interpret it yourself."),
    TVF("better-call-saul", "Better Call Saul", 2015, 8.9, "Crime/Drama",
        "Slippin' Jimmy McGill becomes lawyer Saul Goodman, then Gene the Cinnabon manager.",
        "Gene confesses on the stand for an extra few years and reunites, briefly, with Kim Wexler in prison."),
    TVF("breaking-bad-tv2", "El Camino: A Breaking Bad Movie", 2019, 7.3, "Crime/Drama",
        "Jesse Pinkman flees from his Albuquerque ordeal to a new life in Alaska.",
        "He sells his last El Camino, sends a letter to Brock and disappears north — finally free."),
    TVF("succession", "Succession", 2018, 8.9, "Drama",
        "The Roy children fight over their billionaire father's media empire.",
        "Logan dies; Kendall is voted out; Tom becomes CEO and Shiv silently lets it happen."),
    TVF("ted-lasso", "Ted Lasso", 2020, 8.8, "Comedy/Drama",
        "A folksy American football coach is hired to coach a Premier League side.",
        "Ted returns to Kansas after winning hearts and an FA Cup; AFC Richmond's family endures."),
    TVF("severance", "Severance", 2022, 8.7, "Sci-Fi/Drama",
        "Lumon employees split their work and home memories surgically.",
        "S1: The innies break out for an 'Overtime Contingency' and reveal the truth to the outies."),
    TVF("yellowstone", "Yellowstone", 2018, 8.6, "Drama/Western",
        "The Dutton family fights to keep the largest contiguous ranch in the United States.",
        "S5 part 2: Beth and Rip resolve the Dutton legacy after Kevin Costner's character is written off."),
    TVF("peaky-blinders", "Peaky Blinders", 2013, 8.8, "Crime/Drama",
        "A WWI veteran clan rules Birmingham's streets, betting halls and politics.",
        "S6: Tommy fakes his cancer-induced death and sets fire to his Romany caravan to start over."),
    TVF("vikings", "Vikings", 2013, 8.5, "Drama/History",
        "Ragnar Lothbrok rises from farmer to Norse king and his sons go on to ravage England.",
        "Bjorn's death and Ivar's last battle set the stage for the Great Heathen Army's conquest."),
    TVF("the-last-of-us", "The Last of Us", 2023, 8.7, "Drama/Sci-Fi",
        "Joel smuggles immune teen Ellie across a fungal post-apocalyptic America.",
        "Joel slaughters the Fireflies to save Ellie; he lies to her about the cure — she sees through it."),
    TVF("the-mandalorian-tv", "The Mandalorian", 2019, 8.7, "Sci-Fi/Adventure",
        "A bounty hunter protects The Child from Imperial remnants.",
        "S3: Mando regains his honour, reunites with Bo-Katan and reclaims Mandalore."),
    TVF("andor", "Andor", 2022, 8.4, "Sci-Fi/Drama",
        "Cassian Andor's path from petty thief to Rebellion martyr.",
        "S1: A failed prison break sets the galaxy alight; Maarva's funeral speech sparks the rebellion on Ferrix."),
    TVF("succession-tv2", "Succession Season 4", 2023, 9.0, "Drama",
        "The final battle for Waystar Royco after Logan's funeral.",
        "Tom is named US CEO by Mattson; Shiv stares ahead in the boardroom; Roman drinks alone in a bar."),
    TVF("dark", "Dark", 2017, 8.7, "Sci-Fi/Mystery",
        "A small German town's children disappear across decades.",
        "Jonas and Martha unite to undo the time loop; the original world is restored without them.",
        region="world"),
    TVF("money-heist", "Money Heist (La Casa de Papel)", 2017, 8.2, "Crime/Drama",
        "A criminal mastermind plans an audacious heist on the Royal Mint of Spain.",
        "After a Bank-of-Spain second heist the gang escapes with gold; the Professor and Raquel ride into the sunset.",
        region="world"),
    TVF("squid-game-tv", "Squid Game", 2021, 8.0, "Drama/Thriller",
        "Indebted Koreans compete in deadly children's games for billions of won.",
        "Gi-hun wins, dyes his hair red and turns back at the airport to confront the people behind the games.",
        region="world"),
    TVF("kingdom-kr", "Kingdom", 2019, 8.3, "Horror/Drama",
        "A Joseon-era prince investigates a plague that turns the dead into flesh-eaters.",
        "S2: Lee Chang sacrifices the throne and disappears north to track the resurrection plant.",
        region="world"),
    TVF("rings-of-power", "The Lord of the Rings: The Rings of Power", 2022, 6.8, "Fantasy",
        "Second Age Middle-Earth leading up to the forging of the Rings.",
        "S1: The first three Elven Rings are forged; Sauron is revealed as Halbrand."),
    TVF("the-witcher", "The Witcher", 2019, 8.0, "Fantasy/Adventure",
        "A monster-hunting witcher's destinies tangle with a princess and a sorceress.",
        "S2: Geralt rescues Ciri from Voleth Meir; the trio leaves Kaer Morhen together."),
    TVF("the-bear", "The Bear", 2022, 8.6, "Drama",
        "A fine-dining chef takes over his brother's chaotic Chicago beef stand.",
        "S2: The Bear restaurant opens its 'friends and family' night to mixed but transformative results."),
    TVF("only-murders-in-the-building", "Only Murders in the Building", 2021, 8.1, "Comedy/Mystery",
        "Three true-crime podcasters investigate murders in their NYC apartment building.",
        "S3: A Broadway-set killer is unmasked; new murder kicks off S4."),
    TVF("the-crown", "The Crown", 2016, 8.6, "Biopic/Drama",
        "Six decades of Queen Elizabeth II's reign.",
        "S6: Elizabeth and Philip plan their funerals; the crown is implicitly handed to a new generation."),
    TVF("chernobyl", "Chernobyl", 2019, 9.3, "Drama/History",
        "Soviet scientists and miners try to contain the 1986 nuclear disaster.",
        "Legasov is broken at the trial, hangs himself two years to the day; the truth is finally heard on tape."),
    TVF("when-they-see-us", "When They See Us", 2019, 8.9, "Drama/History",
        "Five Black and Latino teens are wrongfully convicted of the Central Park jogger attack.",
        "Korey Wise is freed when the real attacker confesses; the men are exonerated and settle with NYC."),
    TVF("watchmen-tv", "Watchmen (HBO)", 2019, 8.1, "Sci-Fi/Drama",
        "A masked Tulsa cop confronts a white-supremacist conspiracy decades after the comic.",
        "Angela may have inherited Doctor Manhattan's powers as she steps onto the pool's water in the closing shot."),
    TVF("his-dark-materials", "His Dark Materials", 2019, 7.9, "Fantasy",
        "Lyra Belacqua's quest across parallel worlds and the Authority's empire.",
        "S3: The Authority falls; Lyra and Will say goodbye on the bench in the Botanic Garden."),
    TVF("you", "You", 2018, 7.7, "Thriller",
        "A bookstore manager's obsessive love drives a murder spree across cities.",
        "S4: Joe poses as 'Jonathan' in London; he is exposed and returns to NYC as a tabloid celebrity."),
    TVF("ozark", "Ozark", 2017, 8.5, "Crime/Drama",
        "A financial advisor flees a botched cartel laundering job to the Ozarks.",
        "S4: Marty kills Mel and the Byrdes survive; they remake themselves as Missouri's new powerbrokers."),
]

# ---------------- Indian TV (region=bollywood, kind=tv) ----------------
NEW += [
    TVI("scam-1992", "Scam 1992: The Harshad Mehta Story", 2020, 9.3, "Biopic/Drama",
        "Stockbroker Harshad Mehta's rise and the BSE scam that broke the Indian markets.",
        "Mehta dies in jail awaiting trial; Sucheta Dalal continues to investigate."),
    TVI("scam-2003", "Scam 2003: The Telgi Story", 2023, 8.5, "Biopic/Drama",
        "Counterfeiter Abdul Karim Telgi's stamp-paper scam shakes Maharashtra.",
        "Telgi is arrested, becomes an informant on rival politicians, dies of meningitis behind bars."),
    TVI("the-family-man-tv", "The Family Man", 2019, 8.7, "Spy/Drama",
        "A middle-class TASC officer juggles family life and Indian counter-terror ops.",
        "S2: Srikant prevents a Sri Lankan suicide attack at a summit; a Chennai outbreak hints at S3."),
    TVI("paatal-lok", "Paatal Lok", 2020, 7.8, "Crime/Drama",
        "A jaded Delhi cop investigates an assassination attempt on a celebrity journalist.",
        "S1: Hathiram exposes the elite politician behind the plot; the rotten system endures, but he keeps walking."),
    TVI("delhi-crime-tv", "Delhi Crime", 2019, 8.5, "Crime/Drama",
        "DCP Vartika Chaturvedi leads the Delhi Police hunt for the 2012 Nirbhaya gang.",
        "All six accused are caught and convicted; she watches the press conference, exhausted."),
    TVI("aspirants", "Aspirants", 2021, 9.0, "Drama",
        "Three friends prepare for the UPSC at Delhi's Old Rajinder Nagar.",
        "Abhilash clears the IAS; Guri runs his coaching empire; SK fails again but reconciles with his family."),
    TVI("kota-factory", "Kota Factory", 2019, 8.8, "Drama",
        "Kota's coaching-class life seen through Vaibhav and his cohort.",
        "S3: Jeetu Bhaiya overcomes burnout and rejoins the institute; Vaibhav cracks JEE Advanced."),
    TVI("panchayat", "Panchayat", 2020, 8.9, "Comedy/Drama",
        "A young engineer takes a panchayat secretary post in a UP village while preparing for CAT.",
        "S3: Abhishek leaves Phulera for an MBA; Manju Devi wins the local election; villagers see him off, tearfully."),
    TVI("mirzapur", "Mirzapur", 2018, 8.3, "Crime/Drama",
        "Two brothers are pulled into the carpet-and-opium underworld of eastern UP.",
        "S3: Guddu Pandit kills Munna Tripathi; he and Golu Gupta become the new dons of Mirzapur."),
    TVI("sacred-games", "Sacred Games", 2018, 8.5, "Crime/Drama",
        "A Bombay don's last call to a cop unspools 25 years of city history.",
        "Sartaj defuses the nuclear bomb planted in Mumbai with seconds left; Guruji's apocalypse fails."),
    TVI("jamtara", "Jamtara: Sabka Number Aayega", 2020, 7.4, "Crime/Drama",
        "Jharkhand's phishing-call boom seen from the inside.",
        "S2: The cartel is partially busted but the new generation simply moves to crypto and OTPs."),
    TVI("tvf-tripling", "TVF Tripling", 2016, 9.0, "Comedy/Drama",
        "Three siblings road-trip across India to reset their lives.",
        "S3: They find their parents in Bhutan; the family reunites and Chitvan finally settles down."),
    TVI("permanent-roommates", "Permanent Roommates", 2014, 8.8, "Romance/Comedy",
        "An NRI returns from the US to marry his long-distance girlfriend in Bombay.",
        "S2: Tanya and Mikesh marry on a small terrace; the elders accept them after a season of comic chaos."),
    TVI("flames", "Flames", 2018, 9.0, "Romance/Drama",
        "Two CBSE Class-11 toppers fall in love at a Delhi tuition class.",
        "S4: Rajat and Ishita reconnect at a college reunion; they choose each other again, older and wiser."),
    TVI("special-ops", "Special Ops", 2020, 8.5, "Spy/Drama",
        "A RAW officer hunts a 2001 Parliament-attack mastermind across decades and continents.",
        "S1: Hafiz is killed in Dubai; S2 reopens with a new cyber-terror plot."),
    TVI("the-night-manager-in", "The Night Manager (India)", 2023, 7.7, "Spy/Drama",
        "A Delhi hotelier infiltrates a Mumbai-based arms dealer's inner circle.",
        "S2: Shaan exposes Shelly Rungta and walks away with Kaveri to begin again."),
    TVI("rangbaaz", "Rangbaaz", 2018, 8.3, "Biopic/Crime",
        "The rise of UP gangster Shiv Prakash Shukla.",
        "S1: Shukla is killed by a UP police STF in a Ghaziabad encounter."),
    TVI("breathe", "Breathe", 2018, 7.8, "Thriller",
        "A football coach manipulates the organ-transplant queue to save his dying son.",
        "S1: Danny's son survives; the cop catches him; the system is exposed."),
    TVI("aarya", "Aarya", 2020, 7.9, "Crime/Drama",
        "A wealthy Rajasthani housewife inherits her husband's narcotics business.",
        "S3: Aarya kills Russi and exits the trade; her children begin a clean life abroad."),
    TVI("rocket-boys", "Rocket Boys", 2022, 8.7, "Biopic/Drama",
        "Homi Bhabha and Vikram Sarabhai's parallel paths to India's space and nuclear programs.",
        "S2: India's first satellite Aryabhata is launched; Bhabha dies in the AI 101 crash; Sarabhai carries on alone."),
    TVI("guns-and-gulaabs", "Guns & Gulaabs", 2023, 7.4, "Crime/Comedy",
        "A 1990s small-town opium war among rival families and an unlikely mechanic.",
        "S1: The cartel is broken; Tipu the mechanic finds love with Chandralekha."),
]

# Make sure all entries pass strict id-uniqueness in NEW.
def main():
    if not JSON_PATH.exists():
        print(f"Missing {JSON_PATH}", file=sys.stderr)
        sys.exit(1)
    cur = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    have = {m.get("id") for m in cur}
    seen_in_new = set()
    added = 0
    for n in NEW:
        if n["id"] in seen_in_new:
            print(f"  WARN duplicate id in NEW: {n['id']}", file=sys.stderr)
            continue
        seen_in_new.add(n["id"])
        if n["id"] in have:
            continue
        # Sanity-check required fields
        for k in ("title", "year", "imdb_rating", "synopsis", "actual_ending", "region", "kind"):
            if not n.get(k) and k != "imdb_rating":
                print(f"  WARN missing {k} on {n['id']}", file=sys.stderr)
        cur.append(n)
        added += 1
    JSON_PATH.write_text(json.dumps(cur, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"appended {added} entries; total now {len(cur)}")


if __name__ == "__main__":
    main()
