"""extend_catalog.py — v1.5.0
Append curated Hollywood + TV titles to data/movies.json with region/kind.

Idempotent: skips IDs already in the JSON. Run from anywhere.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "data" / "movies.json"

NEW = [
    # --------- Hollywood top movies (region=hollywood, kind=movie) ----------
    dict(id="inception", title="Inception", year=2010, imdb_rating=8.8,
         genre="Sci-Fi/Thriller",
         synopsis="A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
         actual_ending="Cobb returns home to his children; the spinning top wobbles before the cut to black, leaving reality ambiguous.",
         region="hollywood", kind="movie"),
    dict(id="the-shawshank-redemption", title="The Shawshank Redemption", year=1994, imdb_rating=9.3,
         genre="Drama",
         synopsis="Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
         actual_ending="Andy escapes through a tunnel; Red, paroled, finds him on a Mexican beach in Zihuatanejo.",
         region="hollywood", kind="movie"),
    dict(id="the-godfather", title="The Godfather", year=1972, imdb_rating=9.2,
         genre="Crime/Drama",
         synopsis="The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
         actual_ending="Michael becomes the new Don; the door closes on Kay's face as men kiss his ring.",
         region="hollywood", kind="movie"),
    dict(id="the-dark-knight", title="The Dark Knight", year=2008, imdb_rating=9.0,
         genre="Action/Crime",
         synopsis="Batman raises the stakes in his war on crime, helped by Lt. Gordon and DA Harvey Dent, but a criminal mastermind known as the Joker has plans of his own.",
         actual_ending="Batman takes the blame for Dent's murders and rides into the night, a hunted hero.",
         region="hollywood", kind="movie"),
    dict(id="pulp-fiction", title="Pulp Fiction", year=1994, imdb_rating=8.9,
         genre="Crime/Drama",
         synopsis="The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
         actual_ending="Jules spares the diner robbers, quoting Ezekiel; he and Vincent walk out into the morning.",
         region="hollywood", kind="movie"),
    dict(id="forrest-gump", title="Forrest Gump", year=1994, imdb_rating=8.8,
         genre="Drama/Romance",
         synopsis="The presidencies of Kennedy and Johnson, the events of Vietnam and Watergate unfold from the perspective of an Alabama man with an IQ of 75.",
         actual_ending="Forrest watches young Forrest board the school bus, a feather drifts off into the wind.",
         region="hollywood", kind="movie"),
    dict(id="interstellar", title="Interstellar", year=2014, imdb_rating=8.7,
         genre="Sci-Fi/Drama",
         synopsis="A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
         actual_ending="Cooper reunites briefly with elderly Murph and leaves to find Brand on a habitable planet.",
         region="hollywood", kind="movie"),
    dict(id="the-matrix", title="The Matrix", year=1999, imdb_rating=8.7,
         genre="Sci-Fi/Action",
         synopsis="A hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
         actual_ending="Neo flies into the sky after promising to free humanity from the simulation.",
         region="hollywood", kind="movie"),
    dict(id="gladiator", title="Gladiator", year=2000, imdb_rating=8.5,
         genre="Action/Drama",
         synopsis="A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
         actual_ending="Maximus kills Commodus in the arena and dies, reuniting with his family in the afterlife.",
         region="hollywood", kind="movie"),
    dict(id="the-prestige", title="The Prestige", year=2006, imdb_rating=8.5,
         genre="Drama/Mystery",
         synopsis="After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.",
         actual_ending="Borden's twin reveal collides with Angier's cloning machine; both have hidden one terrible secret.",
         region="hollywood", kind="movie"),
    dict(id="fight-club", title="Fight Club", year=1999, imdb_rating=8.8,
         genre="Drama",
         synopsis="An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
         actual_ending="The Narrator shoots himself to kill Tyler, then watches the buildings explode holding Marla's hand.",
         region="hollywood", kind="movie"),
    dict(id="titanic", title="Titanic", year=1997, imdb_rating=7.9,
         genre="Romance/Drama",
         synopsis="A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
         actual_ending="Rose drops the Heart of the Ocean into the sea; she dreams of reuniting with Jack on the staircase.",
         region="hollywood", kind="movie"),
    dict(id="the-lion-king", title="The Lion King", year=1994, imdb_rating=8.5,
         genre="Animation/Drama",
         synopsis="Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
         actual_ending="Simba defeats Scar, takes his place as king, and presents his cub on Pride Rock.",
         region="hollywood", kind="movie"),
    dict(id="joker", title="Joker", year=2019, imdb_rating=8.4,
         genre="Crime/Drama",
         synopsis="A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
         actual_ending="Arthur dances on a police car amid Gotham riots, anointed as the Joker by his followers.",
         region="hollywood", kind="movie"),
    dict(id="oppenheimer", title="Oppenheimer", year=2023, imdb_rating=8.3,
         genre="Biography/Drama",
         synopsis="The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
         actual_ending="Oppenheimer envisions the chain reaction setting the atmosphere on fire — a metaphor for the world he unleashed.",
         region="hollywood", kind="movie"),
    dict(id="avengers-endgame", title="Avengers: Endgame", year=2019, imdb_rating=8.4,
         genre="Action/Sci-Fi",
         synopsis="After the devastating events of Infinity War, the universe is in ruins. The Avengers assemble once more to undo Thanos's actions.",
         actual_ending="Tony snaps the Stones, sacrificing himself; Cap returns to Peggy and lives a full life.",
         region="hollywood", kind="movie"),
    dict(id="whiplash", title="Whiplash", year=2014, imdb_rating=8.5,
         genre="Drama/Music",
         synopsis="A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor.",
         actual_ending="Andrew's blistering drum solo silences the room; Fletcher gives him the smallest nod.",
         region="hollywood", kind="movie"),
    dict(id="parasite", title="Parasite", year=2019, imdb_rating=8.5,
         genre="Thriller/Drama",
         synopsis="Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
         actual_ending="Ki-woo dreams of buying the house to free his father — but it's only a dream from the same basement.",
         region="world", kind="movie"),
    dict(id="spirited-away", title="Spirited Away", year=2001, imdb_rating=8.6,
         genre="Animation/Fantasy",
         synopsis="During her family's move to the suburbs, Chihiro wanders into a world ruled by gods, witches, and spirits.",
         actual_ending="Chihiro identifies her parents and walks back through the tunnel, never looking back.",
         region="world", kind="movie"),
    dict(id="schindlers-list", title="Schindler's List", year=1993, imdb_rating=9.0,
         genre="Biography/Drama",
         synopsis="In German-occupied Poland, Oskar Schindler becomes concerned for his Jewish workforce after witnessing their persecution.",
         actual_ending="Schindler weeps over the gold ring inscribed 'whoever saves one life saves the world entire.'",
         region="hollywood", kind="movie"),
    dict(id="saving-private-ryan", title="Saving Private Ryan", year=1998, imdb_rating=8.6,
         genre="War/Drama",
         synopsis="Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.",
         actual_ending="Captain Miller dies whispering 'earn this'; old Ryan asks his wife if he's been a good man.",
         region="hollywood", kind="movie"),
    dict(id="the-green-mile", title="The Green Mile", year=1999, imdb_rating=8.6,
         genre="Crime/Drama",
         synopsis="The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder, but who possesses a mysterious gift.",
         actual_ending="John Coffey is executed; old Paul, cursed to outlive everyone, walks his still-living mouse.",
         region="hollywood", kind="movie"),
    dict(id="shutter-island", title="Shutter Island", year=2010, imdb_rating=8.2,
         genre="Mystery/Thriller",
         synopsis="A U.S. Marshal investigates the disappearance of a murderess from a hospital for the criminally insane.",
         actual_ending="Teddy chooses lobotomy: 'live as a monster, or die as a good man?' He walks to the lighthouse.",
         region="hollywood", kind="movie"),
    dict(id="django-unchained", title="Django Unchained", year=2012, imdb_rating=8.5,
         genre="Western/Drama",
         synopsis="With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
         actual_ending="Django blows up Candyland and rides off with Broomhilda, free at last.",
         region="hollywood", kind="movie"),
    dict(id="no-country-for-old-men", title="No Country for Old Men", year=2007, imdb_rating=8.2,
         genre="Crime/Thriller",
         synopsis="Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
         actual_ending="Sheriff Bell narrates a dream of his father riding ahead with a horn of fire — then wakes.",
         region="hollywood", kind="movie"),
    dict(id="la-la-land", title="La La Land", year=2016, imdb_rating=8.0,
         genre="Romance/Musical",
         synopsis="While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.",
         actual_ending="Mia walks into Sebastian's club, exchanges one knowing smile, and leaves with her husband.",
         region="hollywood", kind="movie"),
    dict(id="the-departed", title="The Departed", year=2006, imdb_rating=8.5,
         genre="Crime/Thriller",
         synopsis="An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
         actual_ending="Dignam shoots Sullivan in his apartment; a rat scurries past the railing.",
         region="hollywood", kind="movie"),
    dict(id="gone-girl", title="Gone Girl", year=2014, imdb_rating=8.1,
         genre="Thriller/Mystery",
         synopsis="With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him.",
         actual_ending="Amy returns covered in Desi's blood, traps Nick with a pregnancy, and they smile for the cameras.",
         region="hollywood", kind="movie"),
    dict(id="inglourious-basterds", title="Inglourious Basterds", year=2009, imdb_rating=8.3,
         genre="War/Drama",
         synopsis="In Nazi-occupied France during WWII, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans.",
         actual_ending="Hitler dies in a burning cinema; Aldo carves a swastika into Landa's forehead.",
         region="hollywood", kind="movie"),
    dict(id="goodfellas", title="Goodfellas", year=1990, imdb_rating=8.7,
         genre="Crime/Drama",
         synopsis="The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners.",
         actual_ending="Henry, in witness protection, picks up the morning paper in suburban anonymity.",
         region="hollywood", kind="movie"),

    # --------- Foreign TV (region=hollywood/world, kind=tv) ----------
    dict(id="breaking-bad", title="Breaking Bad", year=2008, imdb_rating=9.5,
         genre="Crime/Drama",
         synopsis="A high school chemistry teacher diagnosed with terminal cancer turns to manufacturing and selling methamphetamine to secure his family's future.",
         actual_ending="Walter dies on the meth lab floor as 'Baby Blue' plays, finally at peace.",
         region="hollywood", kind="tv"),
    dict(id="game-of-thrones", title="Game of Thrones", year=2011, imdb_rating=9.2,
         genre="Fantasy/Drama",
         synopsis="Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
         actual_ending="Bran the Broken is named king; Jon goes north of the Wall; Arya sails west of Westeros.",
         region="hollywood", kind="tv"),
    dict(id="stranger-things", title="Stranger Things", year=2016, imdb_rating=8.7,
         genre="Sci-Fi/Horror",
         synopsis="When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
         actual_ending="The Upside Down has bled into Hawkins; Vecna's storm engulfs the town.",
         region="hollywood", kind="tv"),
    dict(id="squid-game", title="Squid Game", year=2021, imdb_rating=8.0,
         genre="Thriller/Drama",
         synopsis="Hundreds of cash-strapped players accept a strange invitation to compete in children's games for a tempting prize but with deadly stakes.",
         actual_ending="Gi-hun dyes his hair red, turns from his flight, and walks back to find the games.",
         region="world", kind="tv"),
    dict(id="money-heist", title="Money Heist", year=2017, imdb_rating=8.2,
         genre="Heist/Drama",
         synopsis="An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history — stealing 2.4 billion euros from the Royal Mint of Spain.",
         actual_ending="The crew melts the gold, fakes their deaths, and disappears into the world wealthy.",
         region="world", kind="tv"),
    dict(id="the-office-us", title="The Office", year=2005, imdb_rating=9.0,
         genre="Comedy",
         synopsis="A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
         actual_ending="The crew gathers in the parking lot one last time; Pam paints the office on canvas.",
         region="hollywood", kind="tv"),
    dict(id="friends", title="Friends", year=1994, imdb_rating=8.9,
         genre="Comedy/Romance",
         synopsis="Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
         actual_ending="Everyone leaves their keys on the counter and walks out for one last coffee.",
         region="hollywood", kind="tv"),
    dict(id="chernobyl", title="Chernobyl", year=2019, imdb_rating=9.4,
         genre="Drama/History",
         synopsis="A dramatization of the true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl.",
         actual_ending="Legasov hangs himself; his tapes finally tell the truth the state tried to bury.",
         region="hollywood", kind="tv"),
    dict(id="dark", title="Dark", year=2017, imdb_rating=8.8,
         genre="Sci-Fi/Mystery",
         synopsis="A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.",
         actual_ending="Jonas and Martha unravel the bootstrap world; Winden vanishes and they finally cease to exist.",
         region="world", kind="tv"),
    dict(id="peaky-blinders", title="Peaky Blinders", year=2013, imdb_rating=8.8,
         genre="Crime/Drama",
         synopsis="A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.",
         actual_ending="Tommy rides off alone, having broken the bonds of his demons and family — for now.",
         region="hollywood", kind="tv"),
    dict(id="westworld", title="Westworld", year=2016, imdb_rating=8.5,
         genre="Sci-Fi/Drama",
         synopsis="At a Western-themed amusement park, the highly sophisticated androids begin to malfunction and develop free will.",
         actual_ending="Dolores ends humanity's simulation; the hosts awaken into a world they finally control.",
         region="hollywood", kind="tv"),
    dict(id="house-of-cards", title="House of Cards", year=2013, imdb_rating=8.7,
         genre="Political/Drama",
         synopsis="A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
         actual_ending="Claire stabs Doug, becomes President in her own right, and breaks the fourth wall.",
         region="hollywood", kind="tv"),

    # --------- Indian TV (region=bollywood, kind=tv) ----------
    dict(id="sacred-games", title="Sacred Games", year=2018, imdb_rating=8.5,
         genre="Crime/Thriller",
         synopsis="A Bombay police officer receives a phone call from a gangster who tells him to save the city in 25 days, plunging him into Mumbai's underbelly.",
         actual_ending="Sartaj reaches the bunker; the bomb's countdown reaches zero in shocking silence.",
         region="bollywood", kind="tv"),
    dict(id="mirzapur", title="Mirzapur", year=2018, imdb_rating=8.4,
         genre="Crime/Drama",
         synopsis="A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur.",
         actual_ending="Guddu massacres the Tripathis at the wedding; Munna dies; the throne sits empty.",
         region="bollywood", kind="tv"),
    dict(id="scam-1992", title="Scam 1992: The Harshad Mehta Story", year=2020, imdb_rating=9.3,
         genre="Biography/Drama",
         synopsis="Set in 1980s and 90s Bombay, it follows the life of Harshad Mehta, the stockbroker who took the entire stock market on a ride.",
         actual_ending="Harshad collapses in custody; markets crash; the system buries the receipts.",
         region="bollywood", kind="tv"),
    dict(id="the-family-man", title="The Family Man", year=2019, imdb_rating=8.7,
         genre="Action/Drama",
         synopsis="A working man from the National Investigation Agency tries to protect the nation while keeping his family safe.",
         actual_ending="Srikant defuses the bioweapon at the last second; Chellam Sir warns him: it's not over.",
         region="bollywood", kind="tv"),
    dict(id="panchayat", title="Panchayat", year=2020, imdb_rating=8.9,
         genre="Comedy/Drama",
         synopsis="A comedy-drama, which captures the journey of an engineering graduate Abhishek, who joins as a Panchayat secretary in a remote village of UP.",
         actual_ending="Abhishek finally clears CAT but stays one more season — home is where the camera is.",
         region="bollywood", kind="tv"),
    dict(id="delhi-crime", title="Delhi Crime", year=2019, imdb_rating=8.5,
         genre="Crime/Drama",
         synopsis="Inspired by the 2012 Delhi gang rape, the show charts the Delhi Police investigation into the case.",
         actual_ending="Vartika nails the last suspect; the team toasts a small victory in a city that still hurts.",
         region="bollywood", kind="tv"),
    dict(id="kota-factory", title="Kota Factory", year=2019, imdb_rating=9.0,
         genre="Drama",
         synopsis="A black-and-white look at the life of an IIT aspirant in the coaching capital of India.",
         actual_ending="Vaibhav writes JEE; Jeetu Bhaiya watches the boys go, lighting another quiet cigarette.",
         region="bollywood", kind="tv"),
    dict(id="gullak", title="Gullak", year=2019, imdb_rating=8.6,
         genre="Drama/Comedy",
         synopsis="A piggy bank narrates the everyday stories of a middle-class North Indian family.",
         actual_ending="The Mishra family gathers around the dinner table; the gullak smiles and breaks open to start over.",
         region="bollywood", kind="tv"),
    dict(id="aspirants", title="Aspirants", year=2021, imdb_rating=9.1,
         genre="Drama",
         synopsis="A coming-of-age drama based on the life of three best friends preparing to crack the UPSC examinations in Old Rajinder Nagar.",
         actual_ending="SK fails again; Abhilash takes the IAS oath; their friendship outlives the rank list.",
         region="bollywood", kind="tv"),
    dict(id="paatal-lok", title="Paatal Lok", year=2020, imdb_rating=7.5,
         genre="Crime/Drama",
         synopsis="A disillusioned cop is assigned a high-profile case that tumbles him into a darker conspiracy than he could have imagined.",
         actual_ending="Hathi Ram exposes the conspiracy off-record; the system swallows the truth, again.",
         region="bollywood", kind="tv"),
]

def main():
    if not JSON_PATH.exists():
        print("ERR: missing", JSON_PATH); sys.exit(1)
    arr = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    seen = {m["id"] for m in arr}
    added = 0
    for entry in NEW:
        if entry["id"] in seen:
            continue
        # Defaults for fields the schema expects.
        entry.setdefault("poster_url", "")
        entry.setdefault("youtube_id", "")
        arr.append(entry)
        added += 1
    JSON_PATH.write_text(json.dumps(arr, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"appended={added}; total={len(arr)} → {JSON_PATH}")

if __name__ == "__main__":
    main()
